package com.example.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun LearningCenterScreen(onBack: () -> Unit) {
    val scrollState = rememberScrollState()

    Scaffold(
        topBar = {
            CenterAlignedTopAppBar(
                title = { Text("Eco Learning Center", fontWeight = FontWeight.Bold) },
                navigationIcon = {
                    IconButton(onClick = onBack, modifier = Modifier.testTag("learning_back")) {
                        Icon(imageVector = Icons.Default.ArrowBack, contentDescription = "Go Back")
                    }
                },
                colors = TopAppBarDefaults.centerAlignedTopAppBarColors(
                    containerColor = MaterialTheme.colorScheme.background
                )
            )
        }
    ) { innerPadding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .background(MaterialTheme.colorScheme.background)
                .padding(innerPadding)
                .verticalScroll(scrollState)
                .padding(horizontal = 16.dp, vertical = 8.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            // General Statement Card
            Card(
                modifier = Modifier
                    .fillMaxWidth()
                    .testTag("learning_header"),
                shape = RoundedCornerShape(16.dp),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.primary.copy(alpha = 0.08f))
            ) {
                Row(modifier = Modifier.padding(16.dp), verticalAlignment = Alignment.CenterVertically) {
                    Icon(imageVector = Icons.Default.MenuBook, contentDescription = null, tint = MaterialTheme.colorScheme.primary, modifier = Modifier.size(32.dp))
                    Spacer(modifier = Modifier.width(16.dp))
                    Column {
                        Text(
                            text = "Carbon footprint simplified",
                            fontWeight = FontWeight.Bold,
                            fontSize = 14.sp
                        )
                        Text(
                            text = "Read clean explanations on how daily habits stack up.",
                            fontSize = 11.sp,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                    }
                }
            }

            // Cards section
            val materials = listOf(
                LearningCardItem(
                    title = "What is Carbon Footprint & CO₂e?",
                    description = "A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) generated by our actions. It is expressed in 'CO₂e' (Carbon Dioxide equivalent) to express the combined warming effect of different types of emissions in one single unit.",
                    category = "Foundations",
                    icon = Icons.Default.CloudQueue
                ),
                LearningCardItem(
                    title = "Transportation Footprint Insights",
                    description = "Driving standard petrol cars is the single largest footprint contributor for individual commuters. Burning fuel creates heavy CO₂. Shifting to buses, metros, trains, or carpools divides emissions equally among thousands of riders, saving over 60% of transport output.",
                    category = "Transport",
                    icon = Icons.Default.DirectionsBus
                ),
                LearningCardItem(
                    title = "The Food & Diet Correlation",
                    description = "Meat farming generates massive greenhouse gases. Cattle require heavy grain inputs and release potent methane during digestion. Choosing plant-focused meals like vegan organic salads or vegetarian links lowers agricultural footprint output by up to 10x per single serving!",
                    category = "Diet",
                    icon = Icons.Default.Restaurant
                ),
                LearningCardItem(
                    title = "Home Electricity & Energy Saver Tips",
                    description = "Where does wall socket electricity come from? In many regions, power plants still burn coal or natural gas. Unused standby devices left plugged in consume tiny amounts ('vampire power') that accumulate into tons of power plant carbon over standard yearly durations.",
                    category = "Energy & Power",
                    icon = Icons.Default.ElectricBolt
                ),
                LearningCardItem(
                    title = "Shopping, Tech, & Circular Life Cycles",
                    description = "Manufacturing new clothes, phones, and items requires tremendous energy, raw material mining, and transcontinental cargo shipping. Choosing circular reuse models (buying secondhand, recycling packaging) halts extraction cycles, saving lifecycle carbon.",
                    category = "Shopping Habits",
                    icon = Icons.Default.ShoppingBag
                ),
                LearningCardItem(
                    title = "Waste, Methane & Recycling Truths",
                    description = "Traditional sorting rules require attention. Wet food scraps stuffed inside synthetic landfill trash decompose without oxygen, forming highly potent methane gas. Proper composting puts food scraps into clean contact with oxygen, turning waste back into natural soils.",
                    category = "Waste & Compost",
                    icon = Icons.Default.Recycling
                )
            )

            materials.forEach { item ->
                LearningItemCard(item = item)
            }

            Spacer(modifier = Modifier.height(24.dp))
        }
    }
}

data class LearningCardItem(
    val title: String,
    val description: String,
    val category: String,
    val icon: ImageVector
)

@Composable
fun LearningItemCard(item: LearningCardItem) {
    var expanded by remember { mutableStateOf(false) }

    Card(
        modifier = Modifier
            .fillMaxWidth()
            .clickable { expanded = !expanded }
            .testTag("learning_card_${item.title.take(10).replace(" ", "_")}"),
        shape = RoundedCornerShape(16.dp),
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
        elevation = CardDefaults.cardElevation(defaultElevation = 1.dp)
    ) {
        Column(modifier = Modifier.padding(16.dp)) {
            Row(
                modifier = Modifier.fillMaxWidth(),
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.SpaceBetween
            ) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Box(
                        modifier = Modifier
                            .size(36.dp)
                            .background(MaterialTheme.colorScheme.primary.copy(alpha = 0.1f), CircleShape),
                        contentAlignment = Alignment.Center
                    ) {
                        Icon(imageVector = item.icon, contentDescription = null, tint = MaterialTheme.colorScheme.primary, modifier = Modifier.size(18.dp))
                    }
                    Spacer(modifier = Modifier.width(12.dp))
                    Column {
                        Text(
                            text = item.title,
                            fontWeight = FontWeight.Bold,
                            fontSize = 14.sp,
                            color = MaterialTheme.colorScheme.onSurface
                        )
                        Text(
                            text = "Category: ${item.category}",
                            fontSize = 10.sp,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                    }
                }

                Icon(
                    imageVector = if (expanded) Icons.Default.ExpandLess else Icons.Default.ExpandMore,
                    contentDescription = null,
                    tint = MaterialTheme.colorScheme.onSurfaceVariant,
                    modifier = Modifier.size(20.dp)
                )
            }

            if (expanded) {
                Spacer(modifier = Modifier.height(12.dp))
                Divider(color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.06f))
                Spacer(modifier = Modifier.height(10.dp))
                Text(
                    text = item.description,
                    fontSize = 13.sp,
                    color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.8f),
                    lineHeight = 18.sp
                )
            }
        }
    }
}
